title: "Study Notes"
description: "CSE study notes"
email: zayan9111@gmail.com

baseurl: "/my-notes"
url: "https://antilogicz9.github.io"
github_username: antilogicz9

theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.markdown

minima:
  skin: dark

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
